### ISSUE TITLE
Variables from the collection are not created as such

### ISSUE THREAD

**Issue by Gleek** [flashcode/impostman#2]
Thank you for publishing this. I was trying this out but figured that it misses adding the collection variables. 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/3756804/129422947-034e8819-a2d2-449b-9501-9512a6727216.png">

These variables are not generated in a separate environment file and are present inside the exported collection json.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/3756804/129422906-a22308f1-6b26-43c8-a665-a7be89526394.png">

**Comment by flashcode** [comment]
Hi,

You're right, I use variables from the environment but I missed these variables in the collection itself.
I'm going to add this.
