### ISSUE TITLE
Request For 'impostman' To Be On MELPA

### ISSUE THREAD

**Issue by SamuelBanya** [flashcode/impostman#3]
Hey there,

I'm wondering, would it be possible to upload this package onto MELPA?

I ask because I wanted to check this out for work, but noticed I can't find it on MELPA.

Looked really cool, and wanted to check this out for work, but I kind of only use MELPA based packages to avoid packages getting broken over time etc.

Would love to check this out, thanks.

Also, if you do get it up on MELPA, could you please update your installation docs to include a section on 'use-package' as well?

Sam

**Comment by flashcode** [comment]
You're right, I'll make some necessary changes and add it.

**Comment by flashcode** [comment]
I submitted here: https://github.com/melpa/melpa/pull/7818 🤞🏼

**Comment by SamuelBanya** [comment]
Wow @flashcode thanks a ton for this!

I'm stoked to try this next week to put it in my Emacs config :)

Thanks again, wish you the best!

**Comment by SamuelBanya** [comment]
Hey @flashcode 
I made a pull request to make edits to your documentation.

I am COMPLETELY new to using GitHub, as I usually just use Git variants like CGit etc for personal Git projects so this is my first pull request, let me know if you approve, and if it came in successfully :)
https://github.com/flashcode/impostman/pull/4

**Comment by flashcode** [comment]
Done, impostman is now in MEPLA!
