### ISSUE TITLE
Unable to import collection from postman

### ISSUE THREAD

**Issue by Trotter-Wiz-Kiwanis** [flashcode/impostman#5]
Hi, I've tried to use this package. Everytime I'm getting only this outoup:
```
impostman-parse-file: could not parse JSON stream: "'[' or '{' expected near '*'", "<callback>", 1, 1, 1
```

The collection file content:
```
{
	"info": {
		"_postman_id": "c932cc4a-5051-4118-84fd-ef9ffd1238c2",
		"name": "collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "directory",
			"item": [
				{
					"name": "request",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"lastName\": \"Śmietana\",\n    \"firstName\": \"Hanusz\",\n    \"email\": \"mail@mai.pl\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "www.google.pl",
							"host": [
								"www",
								"google",
								"pl"
							]
						}
					},
					"response": []
				}
			]
		}
	]
}
```

**Comment by flashcode** [comment]
Hi @druedain-wicu,

I can import your collection without problems, which version of impostman are you using?
By the way the error mentions "near '*'", but I see no "*" in your collection.

**Comment by Trotter-Wiz-Kiwanis** [comment]
`impostman-version` returns `impostman 0.3.0-snapshot`

> but I see no "" in your collection

I understand. I've prepared the collection above to have a test example. I get the same error for any kind of collection I tried.

----

About my installation: a rather current version of Doom Emacs, Ubuntu 18.04. Impostman installed with just repo adress:

```
(package! impostman
  :recipe (:host github :repo "flashcode/impostman"))
```

Should I use 0.2.0 tag?

Edit: oh man… I went with code from GitHub, instead using published package :facepalm: . Sorry to bother. Retest with published package and will give you feedback.

**Comment by Trotter-Wiz-Kiwanis** [comment]
Okey it's totaly wrong, what I've tried to achieve. I'm really sorry. In fact, my problem is quite different. This ticked should be just closed.

----

My problem is that in interactive mode of function `impostman-import-file` actually I don't know how do I skip question for (optional) environment: https://postimg.cc/q6kXG60w , so Impostman grabs this buffer's text field.

**Comment by flashcode** [comment]
You can just press Enter when prompted for the optional filename, it will ignore it.
